export const GROQ_AI_PROVIDER_TOKEN = 'GROQ_AI_PROVIDER';
export const INTENT_HANDLERS_TOKEN = 'INTENT_HANDLERS';
export const AI_PROVIDER_TOKEN = 'AI_PROVIDER';

export type Intent =
  | 'BEER_RECOMMENDATION'
  | 'SNACK_RECOMMENDATION'
  | 'PAIRING_RECOMMENDATION'
  | 'GENERAL_KNOWLEDGE'
  | 'OFF_TOPIC';
